# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62ff2dce1ea836db6f913ef6d5e07396380d265d24d4e788c120f9f736325ab3879b751aa3bef616c093d3aeb7b5c1bdaf73c3784f3604c7e82d26ac00441f03

test:
  secret_key_base: 422c465128f3e5252b39cd97682734906885190d7a607734c679f42f8c59a97eacb1da810edcd0f6c1e9dd15cd0ac8ee6b1283c8ab01441cc5039ff8c8a922ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
