# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 873d24cd8c08a2e2d2800b46f391ea8c28f0d20bc94cc1af380eb5c924775d0cfc31220ee835e3bdebbb4d65fb35f10b6ca19fe829ca72eb63da657af196b9ab

test:
  secret_key_base: 0b04a90cf0a363a8ed6cb1a4ba1c211b7830572aead5cef5bcb1b2f87669dddc2a4ebaca76c8deb3f7b1c9c2c3544e1238b5e773e9cb8aa5b933d454f57bab39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
